var strings = [
	{
		lang: "PT",
		pub: "Publicação",
		dsc: "Descoberta",
		atv: "Atividades do Processo",
		cmp: "Composição de Processos Publicos",
		passo1_titulo: "Passo 1: Informações do Processo",
		passo1_desc: "Insira as informações sobre o processo",
		passo1_insiraTitulo: "Insira o nome do processo (esse dado será utilizado na descoberta)",
		titulo: "Título",
		passo1_insiraAutor: "Insira o nome do autor",
		autor: "Autor",
		passo1_insiraVersao: "Insira a versão",
		versao: "Versão",
		description: "Descrição",
		data_publi: "Data de Publicação",
		qtd_atv: "Quantidade de Atividades",
		passo1_insiraDesc: "Insira uma descrição",
		nxt: "Seguinte",
		cancel: "Cancelar",
		no_file: "Nenhum Arquivo Selecionado",
		wait_fin: "Aguarde enquanto a Publicação finaliza",
		passo4: "Passo 4: Interfaces de Processo",
		passo4_desc1: "Selecione as interfaces de processo (WSDL) que serão enviadas",
		passo4_desc2: "Para cada item insira um arquivo WSDL e o nome da interface de processo representada.",
		passo4_desc3: "Para cada arquivo selecionado uma nova linha referente a uma nova interface de processo associada a mesma atividade aparecerá ",
		passo4_desc4: "Caso não utilizar alguma linha deixe ambos campos de arquivo e nome referentes a esta linha vazios. ",
		atividade: "Atividade",
		selecione_arq: "Selecione um arquivo: ",
		digite_nome: "Digite um nome: ",
		fin_pub: "Publicação Finalizada!",
		fin_par1: "Pronto, seu processo foi publicado com sucesso!",
		fin_par2: "Para acessá-lo, utilize a coluna DESCOBERTA, busque pelo título do processo (nome utilizado no momento da publicação) e o selecione na lista. ",
		fin_par3: "Para acessar as informações do processo, clicar duas vezes no nome do processo. Assim, você pode também baixar o XPDL e o BPDL gerado.",
		finish: "Finalizar",
		passo3: "Passo 3: Atividades Públicas",
		passo3_par1: "Selecione quais atividades são publicas.",
		select_all: "Selecionar Todas",
		passo2: "Passo 2: Atividades do Processo",
		passo2_par1: "Selecione as atividades que quer publicar",
		pub_conf: "Deseja publicar o seguinte .xpdl?",
		click_add: "Clique para adcionar um arquivo .xpdl",
		submit: "Submeter",
		procurar_processo: "Procurar processo...",
		no_xpdl: "O Processo em questão não possui um XPDL"


	},
	{
		lang: "EN",
		pub: "Publish",
		dsc: "Discovery",
		atv: "Process Activities",
		cmp: "Composition of Public Processes",
		passo1_titulo: "Step 1: Process Information",
		passo1_desc: "Insert informations about the process",
		passo1_insiraTitulo: "Insert the process title (this information will be used for Discovery)",
		titulo: "Title",
		passo1_insiraAutor: "Insert the Author's name",
		autor: "Author",
		description: "Description",
		data_publi: "Publishing Date",
		passo1_insiraVersao: "Insert the process version",
		versao: "Version",
		passo1_insiraDesc: "Insert a description",
		nxt: "Next",
		cancel: "Cancel",
		no_file: "No File Selected",
		wait_fin: "Please wait while your process finishes publishing",
		passo4: "Step 4: Process Interfaces",
		passo4_desc1: "Select which process interfaces(WSDL) should be sent",
		passo4_desc2: "For each item insert a WSDL File and the nome of the respective process interface.",
		passo4_desc3: "For each file selected a new line will be added",
		passo4_desc4: "In case a line isn't used, leave both the name and file fields empty",
		atividade: "Activity",
		qtd_atv: "Amount of Activities",
		selecione_arq: "Select a File: ",
		digite_nome: "Insert a name: ",
		fin_pub: "Publishing finished!",
		fin_par1: "All set! Your process has been published successfully",
		fin_par2: "To access it, use the DISCOVERY collumn and search for the process' title (inserted during PUBLISHING) and select it from the list. ",
		fin_par3: "In order to view the process informations, click twice at the process' title. There, it is possible to download the XPDL uploaded and the generated BPDL",
		finish: "Finish",
		passo3: "Step 3: Public Activities",
		passo3_par1: "Select which activities are public.",
		select_all: "Select All",
		passo2: "Step 2: Process Activities",
		passo2_par1: "Select which activities should be published",
		pub_conf: "Do you wish to publish this .xpdl?",
		click_add: "Click to upload a .xpdl file",
		submit: "Submit",
		procurar_processo: "Search Process...",
		no_xpdl: "This process has no associated XPDL File"
		
	}
]